export const GET_RESOURCES_SUCCESS = "GET_RESOURCES_SUCCESS";
export const GET_RESOURCES_FAILED = "GET_RESOURCES_FAILED";
export const GET_RESOURCES_PENDING = "GET_RESOURCES_PENDING";

export const GET_ONE_RESOURCES_SUCCESS = "GET_ONE_RESOURCES_SUCCESS";
export const GET_ONE_RESOURCES_FAILED = "GET_ONE_RESOURCES_FAILED";
export const GET_ONE_RESOURCES_PENDING = "GET_ONE_RESOURCES_PENDING";

export const ADD_RESOURCES_SUCCESS = "ADD_RESOURCES_SUCCESS";
export const ADD_RESOURCES_FAILED = "ADD_RESOURCES_FAILED";
export const ADD_RESOURCES_PENDING = "ADD_RESOURCES_PENDING";

export const UPDATE_RESOURCES_SUCCESS = "UPDATE_RESOURCES_SUCCESS";
export const UPDATE_RESOURCES_FAILED = "UPDATE_RESOURCES_FAILED";
export const UPDATE_RESOURCES_PENDING = "UPDATE_RESOURCES_PENDING";

export const DELETE_RESOURCES_SUCCESS = "DELETE_RESOURCES_SUCCESS";
export const DELETE_RESOURCES_FAILED = "DELETE_RESOURCES_FAILED";
export const DELETE_RESOURCES_PENDING = "DELETE_RESOURCES_PENDING";