//USERS ACTION TYPES

export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ONE_USER = "FETCH_ONE_USER";

//RESOURCES ACTION TYPES

export const FETCH_RESOURCES = "FETCH_RESOURCES";

//REVIEWS ACTION TYPES

export const FETCH_ALL_REVIEWS = "FETCH_ALL_REVIEWS";
export const FETCH_ONE_REVIEW = "FETCH_ONE_REVIEW";
export const ADD_ONE_REVIEW = "ADD_ONE_REVIEW";
export const REMOVE_ONE_REVIEW = "REMOVE_ONE_REVIEW";

//FAVORITES ACTION TYPES

export const FETCH_ALL_FAVORITES = "FETCH_ALL_FAVORITES";
export const ADD_ONE_FAVORITE = "ADD_ONE_FAVORITE";
export const REMOVE_ONE_FAVORITE = "REMOVE_ONE_FAVORITE";