export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_FAILED = "GET_TAGS_FAILED";
export const GET_TAGS_PENDING = "GET_TAGS_PENDING";

export const GET_ONE_REC_TAGS_SUCCESS = "GET_ONE_REC_TAGS_SUCCESS";
export const GET_ONE_REC_TAGS_FAILED = "GET_ONE_REC_TAGS_FAILED";
export const GET_ONE_REC_TAGS_PENDING = "GET_ONE_REC_TAGS_PENDING";

export const ADD_TAGS_SUCCESS = "ADD_TAGS_SUCCESS";
export const ADD_TAGS_FAILED = "ADD_TAGS_FAILED";
export const ADD_TAGS_PENDING = "ADD_TAGS_PENDING";

export const UPDATE_TAGS_SUCCESS = "UPDATE_TAGS_SUCCESS";
export const UPDATE_TAGS_FAILED = "UPDATE_TAGS_FAILED";
export const UPDATE_TAGS_PENDING = "UPDATE_TAGS_PENDING";
export const UPDATE_RESOURCEVOTE_SUCCESS = "UPDATE_RESOURCEVOTE_SUCCESS";


export const DELETE_TAGS_SUCCESS = "DELETE_TAGS_SUCCESS";
export const DELETE_TAGS_FAILED = "DELETE_TAGS_FAILED";
export const DELETE_TAGS_PENDING = "DELETE_TAGS_PENDING";