export const GET_RESOURCEVOTES_SUCCESS = "GET_RESOURCEVOTES_SUCCESS";
export const GET_RESOURCEVOTES_FAILED = "GET_RESOURCEVOTES_FAILED";
export const GET_RESOURCEVOTES_PENDING = "GET_RESOURCEVOTES_PENDING";

export const GET_ONE_RESOURCEVOTE_SUCCESS = "GET_ONE_RESOURCEVOTE_SUCCESS";
export const GET_ONE_RESOURCEVOTE_FAILED = "GET_ONE_RESOURCEVOTE_FAILED";
export const GET_ONE_RESOURCEVOTE_PENDING = "GET_ONE_RESOURCEVOTE_PENDING";

export const ADD_RESOURCEVOTES_SUCCESS = "ADD_RESOURCEVOTES_SUCCESS";
export const ADD_RESOURCEVOTES_FAILED = "ADD_RESOURCEVOTES_FAILED";
export const ADD_RESOURCEVOTES_PENDING = "ADD_RESOURCEVOTES_PENDING";

export const UPDATE_RESOURCEVOTE_SUCCESS = "UPDATE_RESOURCEVOTE_SUCCESS";
export const UPDATE_RESOURCEVOTE_FAILED = "UPDATE_RESOURCEVOTE_FAILED";
export const UPDATE_RESOURCEVOTE_PENDING = "UPDATE_RESOURCEVOTE_PENDING";

export const DELETE_RESOURCEVOTES_SUCCESS = "DELETE_RESOURCEVOTES_SUCCESS";
export const DELETE_RESOURCEVOTES_FAILED = "DELETE_RESOURCEVOTES_FAILED";
export const DELETE_RESOURCEVOTES_PENDING = "DELETE_RESOURCEVOTES_PENDING";